[21.03.2020 18:56:29.840] Ошибка в методе [DataBaseConnection.GetConnection()]: Отсутствует строка подключения
[21.03.2020 18:56:29.908] Ошибка в методе [DataAccessLayer.DataAccess.DataBaseConnection.GetConnection()]: Exception of type 'System.Exception' was thrown.
[21.03.2020 18:56:29.966] Ошибка в методе [DataAccessLayer.DataAccess.DataBaseConnection.GetConnection()]: Exception of type 'System.Exception' was thrown.
[21.03.2020 18:56:30.003] Ошибка в методе [DataAccessLayer.DataAccess.DataBaseConnection.GetConnection()]: Exception of type 'System.Exception' was thrown.
[21.03.2020 18:56:30.045] Ошибка в методе [DataAccessLayer.DataAccess.DataBaseConnection.GetConnection()]: Exception of type 'System.Exception' was thrown.
[21.03.2020 18:56:34.042] Ошибка в методе [DataBaseConnection.GetConnection()]: Отсутствует строка подключения
[21.03.2020 18:56:34.078] Ошибка в методе [DataAccessLayer.DataAccess.DataBaseConnection.GetConnection()]: Exception of type 'System.Exception' was thrown.
[21.03.2020 18:56:34.117] Ошибка в методе [DataAccessLayer.DataAccess.DataBaseConnection.GetConnection()]: Exception of type 'System.Exception' was thrown.
[21.03.2020 18:56:34.152] Ошибка в методе [DataAccessLayer.DataAccess.DataBaseConnection.GetConnection()]: Exception of type 'System.Exception' was thrown.
[21.03.2020 18:56:34.186] Ошибка в методе [DataAccessLayer.DataAccess.DataBaseConnection.GetConnection()]: Exception of type 'System.Exception' was thrown.
[21.03.2020 18:56:36.554] Ошибка в методе [DataBaseConnection.GetConnection()]: Отсутствует строка подключения
[21.03.2020 18:56:36.590] Ошибка в методе [DataAccessLayer.DataAccess.DataBaseConnection.GetConnection()]: Exception of type 'System.Exception' was thrown.
[21.03.2020 18:56:36.626] Ошибка в методе [DataAccessLayer.DataAccess.DataBaseConnection.GetConnection()]: Exception of type 'System.Exception' was thrown.
[21.03.2020 18:56:36.659] Ошибка в методе [DataAccessLayer.DataAccess.DataBaseConnection.GetConnection()]: Exception of type 'System.Exception' was thrown.
[21.03.2020 18:56:36.691] Ошибка в методе [DataAccessLayer.DataAccess.DataBaseConnection.GetConnection()]: Exception of type 'System.Exception' was thrown.
